theme: minima
title: My First Github
author: Grillinsky  
email: Martine.grillo@gmail.com 
description: > # this means to ignore newlines until "baseurl:"
  A blog about me learning how to use this site, this tools, and me trying to become a Front-end developer first,
  so i can be the best developer i can.
  
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

# social links
twitter_username: _Cosaseria # DO NOT include the @ character, or else the build will fail!
github_username:  Grillinsky # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
